InterviewTask/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('feedback.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback/urls.py
from django.conf.urls import url

from . import views
from .views import index

urlpatterns = [
    url(r'^$',index,name='list'),
    url(r'^thanks/$',views.thanks),
    url(r'^create/$',views.create_company),
    url(r'^(?P<company_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^reviews/(?P<company_id>[0-9]+)/$', views.review, name='review'),
    url(r'^reviews/create_review/(?P<company_id>[0-9]+)/$', views.create_review, name='review'),
]

feedback/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from _datetime import datetime


class Company(models.Model):
    name = models.CharField(max_length=100)
    tag_line = models.TextField()
    description = models.TextField()
    employee = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    company_pic = models.ImageField(upload_to='./pic_folder/', default='./nologo.jpg')

    def __str__(self):
        return self.name

    def save(self):

        if not self.id and not self.company_pic:
            return

        super(Company, self).save()

        company_pic = Image.open(self.company_pic)
        (width, height) = company_pic.size

        size = (500,350)
        size = (500,350)
        company_pic = company_pic.resize(size, Image.ANTIALIAS)
        company_pic.save(self.company_pic.path)


class Feedback(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    phone_number = models.IntegerField()
    comment = models.TextField()
    timestamp = models.DateTimeField(default=datetime.now(), blank=True)

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

feedback/forms.py
from django import forms
from .models import Company, Feedback

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['name','tag_line','description',]


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['first_name','last_name','phone_number','comment']

feedback/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import CompanyForm,FeedbackForm
import json
import datetime
import graphos

from .fusioncharts import FusionCharts
from .models import Company,Feedback
from django.core.mail import send_mail


data = [
        ['Year', 'Sales', 'Expenses'],
        [2004, 1000, 400],
        [2005, 1170, 460],
        [2006, 660, 1120],
        [2007, 1030, 540]
    ]

def detail(request, company_id):

    try:
        company = Company.objects.get(pk=company_id)
    except Company.DoesNotExist:
        raise Http404("Company does not exist")
    company_list = Company.objects.all()
    context = {
        "company_list": company_list,
        "company": company,

    }
    return render(request,'detail.html',context)


def review(request, company_id):
    if request.POST:
        form = FeedbackForm(request.POST)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect('/thanks')
    else:
        form = FeedbackForm()

    try:
        company = Company.objects.get(pk=company_id)
    except Company.DoesNotExist:
        raise Http404("Company does not exist")
    context = {
        "company": company,
        "form": form,

    }
    return render(request, 'company_reviews.html', context)


def index(request):
    is_employee = request.user.groups.filter(name='Employees').exists()
    is_manager = request.user.groups.filter(name='Managers').exists()

    if is_employee:
        company_list = Company.objects.filter(employee=request.user)
        context = {
            "companies": company_list,
            "is_employee": is_employee,
            "is_manager": is_manager
        }

        return render(request, 'employee_index.html', context)
    elif request.user.is_staff:

        dataSource = {}
        # setting chart cosmetics
        dataSource['chart'] = {
            "caption": "Graph for Companies versus their respective reviews",
            "borderAlpha": "20",
            "canvasBorderAlpha": "0",
            "usePlotGradientColor": "0",
            "xaxisname": "Companies",
            "yaxisname": "Reviews",
            "plotBorderAlpha": "10",
            "showXAxisLine": "1",
            "xAxisLineColor": "#999999",
            "showValues": "0",
            "divlineColor": "#999999",
            "divLineIsDashed": "1",
            "showAlternateHGridColor": "0",
            "exportEnabled": "1"
        }

        reviewsDataSource = {}
        # setting chart cosmetics
        reviewsDataSource['chart'] = {
            "caption": "Number of reviews added",
            "subcaption":"Last Year",
            "borderAlpha": "20",
            "canvasBorderAlpha": "0",
            "usePlotGradientColor": "0",
            "xaxisname": "Months",
            "yaxisname": "Reviews",
            "plotBorderAlpha": "10",
            "showXAxisLine": "1",
            "xAxisLineColor": "#999999",
            "showValues": "0",
            "divlineColor": "#999999",
            "divLineIsDashed": "1",
            "showAlternateHGridColor": "0",
            "exportEnabled": "1"
        }

        reviewsDataSource['data'] = []

        for i in range(1, 13):
            data = {}
            currentMonth = datetime.date(2008, i, 1).strftime('%B')
            data['label'] = currentMonth
            count = 0
            for key in Feedback.objects.all():
                if currentMonth == key.timestamp.strftime("%B"):
                    count = count + 1
            data['value'] = count
            reviewsDataSource['data'].append(data)

        dataSource['data'] = []
        # The data for the chart should be in an array wherein each element of the array is a JSON object as
        # `label` and `value` keys.
        # Iterate through the data in `Country` model and insert in to the `dataSource['data']` list.
        for key in Company.objects.all():
            data = {}
            data['label'] = key.name
            data['value'] = Feedback.objects.filter(company=key).count()
            dataSource['data'].append(data)

        column2D = FusionCharts("column2D", "ex1", "600", "400", "chart-1", "json", dataSource)

        column3D = FusionCharts("column2D", "ex2", "600", "400", "chart-2", "json", reviewsDataSource)

        company_list = Company.objects.all()
        review_list = Feedback.objects.all()
        employees = User.objects.filter(groups__name='Employees')
        managers = User.objects.filter(groups__name='Managers')


        context = {
            "companies": company_list,
            "employees": employees,
            "managers": managers,
            "chart": column2D.render(),
            "chart2": column3D.render(),
            "reviews": review_list,
            "latestReviews": Feedback.objects.order_by('-timestamp')[:5]
        }

        return render(request, 'admin_index.html', context)
    elif is_manager:
        employees = User.objects.filter(groups__name='Employees')
        companies = Company.objects.all()

        context = {
            "employees": employees,
            "companies": companies
        }

        return render(request,'manager_index.html', context)
    else:
        companies = Company.objects.all()

        context = {
            "companies": companies,
        }

        return render(request,'customer_index.html', context)


def thanks(request):
    return render(request,'thank-you.html')

@login_required(login_url='/accounts/login/')
def create_company(request):
    if request.POST:
        form = CompanyForm(request.POST)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect('/thanks')
    else:
        form = CompanyForm()
    return render(request,'create_company.html',{'form':form })

def create_review(request,company_id):
    try:
        company = Company.objects.get(pk=company_id)
    except Company.DoesNotExist:
        raise Http404("Company does not exist")
    if request.POST:
        form = FeedbackForm(request.POST)
        url = '/'
        data = json.dumps(url)

        if form.is_valid():

            instance = form.save(commit=False)
            instance.company = company
            instance.save()
            sendEmployeeEmailOnAddReview(company,form)
            return HttpResponse(data, content_type='application/json')
    else:
        form = FeedbackForm()
    context = {
        "company": company,
        "form": form,

    }

    return render(request,'create_review.html',context)

from django.template.loader import render_to_string

def sendEmployeeEmailOnAddReview(company,form):
    subject, from_email, to = "Tech Greatness.com : A customer has added a review","irungu214@gmail.com", \
                              company.employee.email

    context = {
        "employee": company.employee.get_full_name(),
        "company": company,
        "form": form,
        "first_name": form.cleaned_data['first_name'],
        "last_name": form.cleaned_data['last_name'],
        "comment": form.cleaned_data['comment'],
    }

    msg_plain = render_to_string('add_review_email_template.txt', context)
    msg_html = render_to_string('add_review_email_template.html', context)

    send_mail(subject, msg_plain, from_email, [to], fail_silently=False, html_message=msg_html)

feedback/templates/add_review_email_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
function hideURLbar(){ window.scrollTo(0,1); } </script>

    <title>{% block head_title %}Customer Feedback{% endblock head_title %}</title>

    <!-- Bootstrap core CSS -->
    <link href="../static/feedback/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/feedback/css/font-awesome.css">

    <!-- Custom styles for this template -->
    <link href="../static/feedback/css/shop-homepage.css" rel="stylesheet">
    <link href="../static/feedback/js/jquery.bxslider/jquery.bxslider.css" rel="stylesheet">
<link href="../static/feedback/css/colorbox.css" rel="stylesheet">

    <link href="../static/feedback/css/style.css" rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="{% static 'feedback/css/bootstrap.css' %}">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700,800&amp;subset=latin-ext" rel="stylesheet">

</head>


<body>

    <div class="container">

        <p>Hi, {{ employee }},</p><br />
        <p> A customer has added the following review for {{ company.name }}  </p>
     <table >
         <tr>
             <th>
                 Name :
             </th>
             <td>
                 {{ first_name }} {{ last_name }}
             </td>
         </tr>
          <tr>
             <th>
                 Comment :
             </th>
             <td>
                 {{ comment }}
             </td>
         </tr>
     </table>
        <a class="btn btn-primary" href="http://127.0.0.1:8000/reviews/{{ company.id }}">View All Reviews</a>

    </div>

 <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Customer Feedback 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="../static/feedback/js/jquery.min.js"></script>
    <script src="../static/feedback/js/popper.min.js"></script>
    <script src="../static/feedback/js/bootstrap.min.js"></script>
    <script src="../static/feedback/js/jquery.bxslider/jquery.bxslider.min.js"></script>
    <script src="../static/feedback/js/jackmoore-colorbox-0662982/jquery.colorbox-min.js"></script>
    <script src="../static/feedback/js/app.js"></script>

</body>
</html>

feedback/templates/admin_index.html
{% extends "base.html" %}

{% block content %}
<div class="page-container" style="padding-top: 30px; padding-bottom: 10px">

<div class="row" style="padding-bottom: 30px">
        <div class="col-md-4">
<div class="panel panel-default" style="height:100%; background: #ff4a43">
      <div class="panel-body">
    <h3>Managers</h3>
          <h4>{{ managers.count }}</h4>
      </div>
</div>
</div>


<div class="col-md-4">
           <div class="panel panel-default" style="height:100%; background:#22beef">
      <div class="panel-body">
      <h4>Companies</h4>
         <h4>{{ companies.count }}</h4>
     </div>
     </div>
</div>

<div class="col-md-4">

           <div class="panel panel-default" style="height:100%; background:#a2d200">
      <div class="panel-body">
      <h3>Reviews</h3>
         <h4>{{ reviews.count }}</h4>
     </div>
     </div>

</div>
</div>

<div class="row" style="padding: 20px 20px 20px 1px; background: lightgrey;">
    <div class="col-md-12">
    <ol class="statistics">
    <li>
    <h3>Statistics</h3>
    </li>
    </ol>
    </div>

    <div class="col-md-6 graph">

         <div class="panel panel-default" style="height:100%">
      <div class="panel-body">
          <div id="chart-1"></div>
        {{ chart | safe }}
      </div>
         </div>
    </div>
     <div class="col-md-6 graph">
         <div class="panel panel-default" style="height:100%">
      <div class="panel-body">
          <div id="chart-2"></div>
        {{ chart2 | safe }}
      </div>
         </div>
    </div>

</div>
<div class="row" style="background: lightgrey">
    <div class="col-sm-6">
        <div class="card">
            <div class="row tabletop tableright">
                <div class="col-md-6 col-sm-6 col-xs-6">
                    <h3>October 2017</h3>
                    <p>REPORT</p>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-6 textright">
                    <h2>{{ latestReviews.count }} reviews</h2>
                </div>

            </div>
            <div class="widget-body">
                <table class="table">
                    <tr>
                        <th>REVIEW</th>
                        <th>COMPANY</th>
                        <th>DATE SUBMITTED</th>
                    </tr>
                    {% for review in latestReviews %}
                    <tr>

                            <td>{{ review.first_name }}</td>
                            <td>{{ review.company.name }}</td>
                            <td>{{ review.timestamp }}</td>

                    </tr>
                          {% endfor %}
                </table>
            </div>

        </div>
    </div>
</div>
</div>
{% endblock %}

feedback/templates/as_html.html
{{ html }}
{{ js }}

feedback/templates/company_reviews.html
{% extends "base.html" %}

{% block content %}
    <!-- Page Content -->
    <div class="container">

        <div class="row">
            <!-- /.col-lg-3 -->

            <div class="col-lg-12">

                <div class="card mt-4">
                    <table>
                        <tr>
                            <td style="width: 30%">
                                <img class="card-img-top img-fluid" src="{{ company.company_pic.url }}" alt=""
                                     max-height="400" max-width="900">
                            </td>
                            <td style="width: 70%;padding: 0px 10px 0px 20px;vertical-align: top;">
                                <h3 class="card-title">{{ company.name }}</h3>
                                <p class="card-text">{{ company.description }}</p>
                                <div style="    position: absolute;
    bottom: 30px;
    right: 215px;"><span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
                                    4.0 stars
                                </div>
                            </td>
                        </tr>
                    </table>

                    <div class="card-body">

                    </div>
                </div>
                <!-- /.card -->

                <div class="card card-outline-secondary my-4">
                    <div class="card-header">
                        Company Reviews
                    </div>
                    <div class="card-body">
                        {% for review in company.feedback_set.all %}
                            <p>{{ review.comment }}</p>
                            <small class="text-muted">Posted by {{ review.first_name }}
                                on {{ review.timestamp.date }}</small>
                            <hr>
                        {% endfor %}
               <!--end .accordion-section-->
                    </div>
                </div>
            </div>
        <!-- /.col-lg-9 -->

    </div>
    <div class="row" style="
    padding-bottom: 20px;
">
        <div class="col-lg-12" style="padding-left: 245px">
                 <div class="accordion">
                            <div class="accordion-section">
                                <a class="accordion-section-title btn btn-primary" href="#accordion-1"
                                   class="btn btn-primary">Leave a Review</a>
                                <div id="accordion-1" class="accordion-section-content">
                                    <form id="SubmitReviewForm" action="" method="post">
                                        <table class="table">

                                        <tr>
                                                {% csrf_token %}
                                                {{ form.non_field_errors }}
                                                <div class="form-group col-md-12">
                                                    <td>
                                                    {{ form.first_name.errors }}
                                                    <label for="{{ form.first_name.id_for_label }}">First Name:</label>

                                                </td>
                                                    </div>
                                        </tr>
                                            <tr>
                                                  <div class="form-group col-md-12">
                                            <td>
                                                    {{ form.first_name }} {{ form.last_name }}

                                            </td>
                                                  </div>

                                        </tr>
                                            <tr>

                                                <div class="form-group">
                                                    <td>
                                                    {{ form.phone_number.errors }}
                                                    <label for="{{ form.phone_number.id_for_label }}">Phone Number:</label>
                                                    </td>
                                                </div>
                                            </tr>
                                            <tr>
                                                 <td>
                                                        {{ form.phone_number }}
                                                    </td>
                                            </tr>
                                            <tr>

                                                <div class="form-group">
                                                    <td>
                                                    {{ form.comment.errors }}
                                                    <label for="{{ form.comment.id_for_label }}">Comment</label>
                                                    </td>

                                                </div>

                                            </tr>
                                            <tr>
                                                <td>
                                                        {{ form.comment }}
                                                    </td>
                                            </tr>
                                        <tr>
                                            <td>
                                                <input id="SubmitReviewButtonOnReviewsPage" class="btn btn-primary"
                                                       data-id="{{ company.id }}" type="submit" value="Submit"/></td>
                                        </tr>
                                        </table>
                                    </form>
                                </div>
                            </div><!--end .accordion-section-content-->
                        </div>
    </div>
    </div>
    </div>

{% endblock content %}

feedback/templates/contact.html
<html>
<body>
<form action="/your-name/" method="post">
{% csrf_token %}
{{ form }}
<input type="submit" value="Submit" />
</form>
<p> <a href="{% url 'logout' %}">logout</a>
      </p>
</body>
</html>

feedback/templates/createemployee.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="." method="post">
{% csrf_token %}
{{ form }}
<input type="submit" value="Submit" />
</form>

<p> <a href="#">Create Employee</a>
      </p>

</body>
</html>

feedback/templates/customer_index.html
{% extends "base.html" %}

{% block content %}

    <!-- Page Content -->
    <div class="container" style="
    margin-top: 20px;
    margin-bottom: 60px;
">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">Home</h1>
                <div class="list-group">

                    {% for company in companies %}
                        <div class="list-group-item">

                            <a href="/{{ company.id }}" class="">{{ company.name }}</a>
                            <p class="card-text">{{ company.tag_line | truncatechars:40 }}</p>

                        </div>

                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">



                <div class="row">

                    {% for company in companies %}

                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#"><img class="card-img-top" src="{{ company.company_pic.url }}" alt=""
                                                 height="250" width="700"></a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="/{{ company.id }}">{{ company.name }}</a>
                                    </h4>
                                    {% if company.feedback_set.all %}
                                        <div class="reviews" style="margin-bottom: 0px">
                                            {% for review in company.feedback_set.all %}


                                                <p style="text-align: center; margin-bottom: 0px">
                                                <b style="color: black">{{ review.first_name }}</b><br>
                                                {{ review.comment }}<br/>


                                            {% endfor %}

                                        </div>
                                        <a class="btn btn-primary" href="/reviews/{{ company.id }}">View All Reviews</a>
                                    {% else %}
                                        <p style="font-style: italic; padding: 32px;"><i>This company is yet to have any feedback</i></p>
                                        <a id="CustomerReviewButton" class="btn btn-primary" href="/reviews/create_review/{{ company.id }}">Add A Review</a>
                                    {% endif %}

                                </div>
                                <div class="card-footer">
                                    <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                                </div>
                            </div>
                        </div>

                    {% endfor %}


                    <!-- /.row -->
                </div>

            </div>
        </div>
            <!-- /.col-lg-9 -->

        </div>
        <!-- /.row -->

    </div>
    </div>
{% endblock %}

feedback/templates/detail.html
{% extends "base.html" %}

{% block content %}
    <!-- Page Content -->
    <div class="container" style="
    margin-top: 60px;
">

      <!-- Portfolio Item Heading -->
      <h1 class="my-4">{{ company.name }}
      </h1>

      <!-- Portfolio Item Row -->
      <div class="row">

        <div class="col-md-8" height="350" width="900">
          <img class="img-fluid" href="/{{ company.id }}" src="{{ company.company_pic.url }}" alt="{{ company.name }}" >
        </div>

        <div class="col-md-4">
          <h3 class="my-3">Company Description</h3>
          <p>{{ company.description }}</p>
          <h3 class="my-3">Employee : {{ company.employee.get_full_name }}</h3>
            <a class="btn btn-primary" href="/reviews/{{ company.id }}" >View Company Reviews</a>
        </div>

      </div>
      <!-- /.row -->

      <!-- Related Projects Row -->
      <h3 class="my-4">Related Companies</h3>

      <div class="row">

          {% for relatedCompany in company_list %}

        <div class="col-md-3 col-sm-6 mb-4">
          <a href="/{{ relatedCompany.id }}">
            <img class="img-fluid" src="{{ relatedCompany.company_pic.url }}" alt="" href="/{{ relatedCompany.id }}">
          </a>
        </div>
          {% endfor %}

      </div>
      <!-- /.row -->

    </div>

{% endblock content %}

feedback/templates/employee_index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="container" style="
    margin-top: 60px;
">

      <div class="row">

        <div class="col-lg-3">

          <h1 class="my-4">Home</h1>
          <div class="list-group">

               {% for company in companies %}
                   <div class="list-group-item">

            <a href="/{{ company.id }}" class="">{{ company.name }}</a>
                   <p class="card-text">{{ company.tag_line | truncatechars:40 }}</p>

                   </div>

              {% endfor %}
          </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

          <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
            <ol class="carousel-indicators">
                {% for company in companies %}
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                 {% endfor %}

            </ol>
            <div class="carousel-inner" role="listbox">

              <div class="carousel-item active" style="
    width: 900px;
    height: 350px;
">
                <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
              </div>
                {% for company in companies %}
                    <div class="carousel-item" style="
    width: 900px;
    height: 350px;
">
                <img class="d-block img-fluid" style="height:100% !important; margin: 0 auto; background:#6FCDE3; -moz-border-radius: 100px; -webkit-border-radius:100px;" href="/{{ company.id }}" src="{{ company.company_pic.url }}" alt="{{ company.name }}" height="350" width="900">
              </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>

          <div class="row">

              {% for company in companies %}

            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="{{ company.company_pic.url }}" alt="" height="250" width="700"></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="/{{ company.id }}">{{ company.name }}</a>
                  </h4>
                {% if company.feedback_set.all %}
                            <div class="reviews" style="margin-bottom: 0px">
                  {% for review in company.feedback_set.all %}


										<p style="text-align: center; margin-bottom: 0px">
                                            <b style="color: black">{{ review.first_name }}</b><br>
                                                {{ review.comment }}<br />


                                            {% endfor %}

                                    </div>
                    <a class="btn btn-primary" href="/reviews/{{ company.id }}" >View All Reviews</a>
                {% else %}
                    <p style="
    font-style: italic;
"><i>This company is yet to have any feedback</i></p>
                {% endif %}

                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
                   </div>

                {% endfor %}


          <!-- /.row -->
          </div>

        </div>
        <!-- /.col-lg-9 -->

      </div>
      <!-- /.row -->

    </div>
    </div>

<!-- content -->


{% endblock content %}

feedback/templates/manager_index.html
{% extends "base.html" %}

{% block content %}
    
    <ul>
    {% for employee in employees %}
        <li>{{ employee.get_full_name }}</li>
    {% endfor %}
    </ul>

{% endblock %}

feedback/templates/thank-you.html
{% extends 'base.html' %}
{% block content %}
    <p>Thank you for addition!</p>
{% endblock %}